name: workus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-178.0.dev <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  flex_color_scheme: ^7.3.1
  flex_seed_scheme: ^1.5.0
  flutter:
    sdk: flutter
  flutter_ringtone_player: ^4.0.0+3
  flutter_riverpod: ^2.5.1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  material_symbols_icons: ^4.2744.0
  media_kit: ^1.1.10+1
  mockito: ^5.4.4
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie_animations/
    - assets/quotes/
    - assets/alarm_sounds/
